# example /etc/rrdstat.yml config file
rrddir: ''
rrdprefix: thishost-
persistfile: /tmp/rrdstat.yml
daemonhost: your_rrd_server
daemonport: 12345
heartbeat: 600
# avg: 5min, 30min, 2h, 12h, max: 12h
rradefault: "RRA:AVERAGE:0.5:1:6000 RRA:AVERAGE:0.5:6:6000 RRA:AVERAGE:0.5:24:6000 RRA:AVERAGE:0.5:144:6000  RRA:MAX:0.5:144:6000"
sources:
  interfaces:
    main: eth0

  disks:
    root: /
    usr: /usr
    var: /var
    home: /home

  sensors:
    hddtemp: 
      disk1: /dev/sda
      disk2: /dev/sdb
    sensors: 
      cpu1: Core 0
      cpu2: Core 1
      cpu3: Core 2
      cpu4: Core 3
      case: CPU/casing Temp
      board: Board Temp
      fan1: CPU Fan
      fan2: VGA Fan

  meminfo: 1
  cpustats: 1
  iptables:
    logdrop: DROP
  maillog: /var/log/maillog
  newslog: /var/log/news/news


