#!/usr/bin/perl
use strict;
use Mojolicious::Commands;

# findbin makes plack misbehave under mod_perl, even with ->again.
use lib "$ENV{MOJO_HOME}/lib";	

# Start command line interface for application
Mojolicious::Commands->start_app('Mrrd');
