#!/usr/bin/perl
use strict;
use Mojolicious::Commands;
use FindBin;
FindBin->again;									# crucial for mod_perl

use lib "$FindBin::Bin/../lib";

# Start command line interface for application
Mojolicious::Commands->start_app('Mrrd');
